[workspace]

members = [
    "solidity-bindgen",
    "solidity-bindgen-macros",
]

[patch.crates-io]
ethabi = { git = "https://github.com/graphprotocol/ethabi" }
#ethabi = { path = "../ethabi/ethabi" }
web3 = { git = "https://github.com/tomusdrw/rust-web3" }